input_dir: '../inputs'
output_dir: '../outputs'
device: 'cuda'
# any argument related to individual model
# all model yaml should have these  
model_name: go-emotion-pool-tiny
dataset_source_path: go-emotions-google-emotions-dataset/go_emotions_dataset.csv
train_dataset_path: train_set_compact.csv
test_dataset_path: test_set_compact.csv
test_split: 0.2
validation_split_from_train: 0.2
seed: 0
drop_insignifiant: true
checkpoint_dir: checkpoints
emotions:
- admiration
- amusement
- anger
- annoyance
- approval
- caring
- confusion
- curiosity
- desire
- disappointment
- disapproval
- disgust
- embarrassment
- excitement
- fear
- gratitude
- grief
- joy
- love
- nervousness
- optimism
- pride
- realization
- relief
- remorse
- sadness
- surprise

# trainining
train_batch_size: 16
eval_batch_size: 16
train_epochs: 20
save_steps: 3000
validation_steps: 3000
learning_rate: 0.0001
grad_clip_max: 1
weight_decay: 0.00001
warmup_ratio: 0.1 

# model
classification_threshold: 0.4
sentence_max_len: 62

# model specific
encoder_name: prajjwal1/bert-tiny
fc_hiddens:
 - 50 
 - 50 
dropout_p: 0.1